openapi: 3.0.0
info:
  title: uselessfacts v2
  description: |
    Get Random Useless Facts. You can change language parameter to get fact in different language. Default is "en".
  version: 1.0.0
servers:
  - url: https://uselessfacts.jsph.pl/api/v2
tags:
  - name: facts
paths:
  /facts/random:
    get:
      operationId: getRandom
      description: Endpoint fetches a random fact.
      tags:
        - facts
      summary: Random Useless Fact
      parameters:
        - name: language
          in: query
          schema:
            type: string
          description: Desired language identifier
          example: en
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                id: 5ca2a61f05c5ff5ba6432ace47fa2636
                text: >-
                  The world`s record for keeping a Lifesaver in the mouth with
                  the hole intact is 7 hrs 10 min.
                source: djtech.net
                source_url: http://www.djtech.net/humor/useless_facts.htm
                language: en
                permalink: >-
                  https://uselessfacts.jsph.pl/api/v2/facts/5ca2a61f05c5ff5ba6432ace47fa2636
        '500':
          description: Internal Server Error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                status: 500
                code: server_error
  /facts/today:
    get:
      operationId: getTodayFact
      description: Endpoint fetches today's fact.
      tags:
        - facts
      summary: Today's Useless Fact
      parameters:
        - name: lanugage
          in: query
          schema:
            type: string
          description: Desired language identifier
          example: en
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                id: 69e0e143f4adafd23a7c216a6087c4ec
                text: >-
                  The name for Oz in the "Wizard of Oz" was thought up when the
                  creator, Frank Baum, looked at his filing cabinet and saw A-N,
                  and O-Z; hence the name "OZ."
                source: djtech.net
                source_url: http://www.djtech.net/humor/useless_facts.htm
                language: en
                permalink: >-
                  https://uselessfacts.jsph.pl/api/v2/facts/69e0e143f4adafd23a7c216a6087c4ec
        '500':
          description: Internal Server Error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                status: 500
                code: server_error